### ISSUE TITLE
Incomplete name recognition in channel ID

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#151] opened 2014-07-14 14:13 UTC
If I pass the detector name `"SiR1-sum-F"` (obtained from TSetupData) to the `IDs::channel(string)` constructor, I get back the string "Unknown". 

I haven't looked in any detail as to why this is the case.

**Comment by benkrikler** [comment] 2014-07-14 15:26
I just had a quick look at the code behind this again and it's not
immediately obvious what the cause is.  One guess is that SiR1_sum-F
matches the first '_s' in the '_sum' part as the slow / fast string.  The
rest of the algorithm gets messed up then cause the rest of the string
isn't handled correctly.

**Comment by benkrikler** [comment] 2014-08-01 20:05
This should be fixed now and for future purposes I've added a specific unit test to check this channel.

**Closed as completed by benkrikler** 2014-08-01 20:05 UTC
Labels: bug, Rootana ID classes
