### ISSUE TITLE
Different TMEs containing the same TDP?

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#238] opened 2014-10-01 16:28 UTC
I've been reading through issue #110 and Ben's presentation in [elog:163](https://muon.npl.washington.edu/elog/mu2e/Analysis-R13/163) to try and think the answer is no. Even if the answer is yes, I think there may still be a bug.

So I'm looking into the asymmetry in the numbers of protons in the silicon arms for the momentum scans we did, to see if that gives us any indication of the stopping depth in the target.

I'm using the latest production.cfg file and have added a module to loop through TMuonEvents like so:

``` C++
int PlotTME_SiliconArmAsymmetry::ProcessEntry(TGlobalData *aData, const TSetupData* aSetup){
  //gMuonEvents.clear();                                                                                                                              
  for (MuonEventList::const_iterator i_muonEvent = gMuonEvents.begin(); i_muonEvent != gMuonEvents.end(); ++i_muonEvent) {
    int n_sources = (*i_muonEvent)->GetNumSources();

    for (int i_source = 0; i_source < n_sources; ++i_source) {
      IDs::source i_sourceID = (*i_muonEvent)->GetSource(i_source);
      int n_source_pulses = 0;
      if (i_sourceID.matches(IDs::channel("SiR2"))) {
        //      std::cout << "TME #" << i_muonEvent - gMuonEvents.begin() << ": " << (*i_muonEvent)->GetSource(i_source).str() << std::endl;          
        n_source_pulses = (*i_muonEvent)->NumPulses(i_sourceID);

        fRightCounter += n_source_pulses;
      }
      else if (i_sourceID.matches(IDs::channel("SiL2"))) {
        std::cout << "TME #" << i_muonEvent - gMuonEvents.begin() << ": " << (*i_muonEvent)->GetSource(i_source).str() << std::endl;
        n_source_pulses = (*i_muonEvent)->NumPulses(i_sourceID);
        fLeftCounter += n_source_pulses;
      }

      for (int index = 0; index < n_source_pulses; ++index) {
        const TDetectorPulse* i_pulse = (*i_muonEvent)->GetPulse(i_sourceID, index);

        std::cout << i_sourceID << ": Amplitude of pulse = " << i_pulse->GetAmplitude() << std::endl;
      }
    }
  }
  return 0;
}
```

So I'm essentially looking for the number of pulses in SiR2 and SiL2 and increasing a counter. This resulted in no correlation between asymmetry and scaling factor of the muon beam so I'm looking to put in an amplitude cut to cut out any electrons that could be coming from anywhere (i.e. not the target).

However, when I print the amplitude of the pulse, I get:

```
Processed  13/16  (81%)
Processed  14/16  (87%)
TME #0: SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}: Amplitude of pulse = -99999
TME #1: SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}: Amplitude of pulse = -99999
TME #2: SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}: Amplitude of pulse = -99999
TME #3: SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}: Amplitude of pulse = -99999
TME #4: SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}: Amplitude of pulse = -99999
TME #5: SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}: Amplitude of pulse = -99999
TME #6: SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}: Amplitude of pulse = -99999
TME #7: SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}: Amplitude of pulse = -99999
...
```

for quite a while until here:

```
...
TME #192: SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}: Amplitude of pulse = -99999
TME #193: SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}: Amplitude of pulse = -99999
TME #194: SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}: Amplitude of pulse = 552.02
SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}: Amplitude of pulse = -99999
TME #195: SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}: Amplitude of pulse = 552.02
SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}: Amplitude of pulse = -99999
TME #196: SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}: Amplitude of pulse = 552.02
SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}: Amplitude of pulse = -99999
TME #197: SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}: Amplitude of pulse = 552.02
SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}: Amplitude of pulse = -99999
...
```

where I seem to be getting the same TDP in each TME.

It stays like this until the end of the event:

```
...
TME #594: SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}: Amplitude of pulse = 552.02
SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}: Amplitude of pulse = -99999
TME #595: SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}: Amplitude of pulse = 552.02
SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}: Amplitude of pulse = -99999
Processed  15/16  (93%)
PlotTDPs: Warning: fitting to 2D amplitude plots failed with status: -1 for SiL1-1#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
PlotTDPs: Warning: fitting to 2D amplitude plots failed with status: -1 for SiL1-2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
PlotTDPs: Warning: fitting to 2D amplitude plots failed with status: -1 for SiL1-3#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
PlotTDPs: Warning: fitting to 2D amplitude plots failed with status: -1 for SiL1-4#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
PlotTDPs: Warning: fitting to 2D amplitude plots failed with status: -1 for SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
PlotTDPs: Warning: fitting to 2D amplitude plots failed with status: -1 for SiR1-1#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
PlotTDPs: Warning: fitting to 2D amplitude plots failed with status: -1 for SiR1-2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
PlotTDPs: Warning: fitting to 2D amplitude plots failed with status: -1 for SiR1-3#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
PlotTDPs: Warning: fitting to 2D amplitude plots failed with status: -1 for SiR1-4#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
PlotTDPs: Warning: fitting to 2D amplitude plots failed with status: -1 for SiR2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
Left : Right = 998 : 0
Asymmetry ((N_L - N_R)/(N_L + N_R)) = 1

Finished processing data
```

I'm not entirley sure how the TME generator works so does anyone have any ideas?

**Comment by AndrewEdmonds11** [comment] 2014-10-01 17:31
On a somewhat related note, how can you get `TDetectorPulse::GetAmplitude()` to return the amplitude of the slow pulse (by default it is set to fast). The function asks for a `ParentChannel_t`:

``` C++
double GetAmplitude(ParentChannel_t ch=kFast)const{ 
            TDP_GetField(ch,Amplitude); }
```

but when I try the following in my own code:

``` C++
i_pulse->GetAmplitude(ParentChannel_t::kSlow)
```

or

``` C++
i_pulse->GetAmplitude(TDetectorPulse::ParentChannel_t::kSlow)
```

It says:

```
src/plotters/PlotTME_SiliconArmAsymmetry.cpp:60: error: ‘ParentChannel_t’ has not been declared
```

even though the enum is in the public space of TDetectorPulse:

``` C++
class TDetectorPulse : public TObject {
    public:
        enum ParentChannel_t { kSlow,kFast, kNumParents};
```

Is this deliberate or am I trying to do something wrong?

Also, are there functions to get the slow and fast parent ID that I'm not seeing?

**Comment by jrquirk** [comment] 2014-10-01 17:32
kSlow is defined in the namespace of the enumeration. So TDetectorPulse::kSlow is what you want. I've been confused by enums in this way myself. kSlow is just of type TDetectorPulse::ParentChannel_t.

**Comment by AndrewEdmonds11** [comment] 2014-10-01 17:39
Haha, the one permutation I didn't try. Thanks, John :)

**Comment by benkrikler** [comment] 2014-10-02 08:09
If multiple muons arrive within a short space of time they would each be given the same SiL2 TDP by design of the muon centred tree. Those TMEs should all be flagged as muon pile-up though.

But you say it stays that way until the end of the event, and it seems hard to imagine some 400 muons arrive in 10us... In which case this would look like a bug.  I just looked back at my TME validation work and remember that 100%  of TMEs were flagged as muon pile-up which was clearly not right even at the time.  So my guess is that this is probably what was causing that issue...  

Unfortunately the cause of this is not immediately obvious to me so I'm going to have to dig around a bit more...

**Comment by AndrewEdmonds11** [comment] 2014-10-02 15:39
So, looking in `FixedWindowMEGenerator` it seems the window is set to "10":

``` C++
FixedWindowMEGenerator::FixedWindowMEGenerator(TMEGeneratorOptions* opts):
        TVMuonEventGenerator("FixedWindow",opts){
        fEventWindow=opts->GetDouble("event_window",10);
}
```

I think that this is 10 ns based on the fact that the time of the pulses is in that unit. Is what we intended for the window width? It seems a bit small to me but, in any case, I don't think it would actually solve the problem we're having if it's supposed to be longer.

**Comment by AndrewEdmonds11** [comment] 2014-10-02 18:07
Ok, so I've added a few cout statements to see what's going on and I think it's because each TME starts adding TDPs from the start of the vector and only stops when it goes outside of the time window i.e the beginning of the time window is not checked.

Here's the first TME I get, with the time of the central muon and some lines saying what the module is trying to do (NB I've extended the window to 10us in my config file):

```
TME #0 (t = 257590) : 
Looking for pulses between 247590 and 267590 for muSc#PassThrough#{alias=detector_pulses}{time_difference=1}
TDP 0x1b404e0, t = 257590
Adding pulses from muSc#PassThrough#{alias=detector_pulses}{time_difference=1} between 0x1b404e0 and 0x1b3fc30
Looking for pulses between 247590 and 267590 for Ge#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
Adding pulses from Ge#MaxTimeDiff#{alias=detector_pulses}{time_difference=1} between 0x1b4c130 and 0x1b4c130
Looking for pulses between 247590 and 267590 for NDet#PassThrough#{alias=detector_pulses}{time_difference=1}
Adding pulses from NDet#PassThrough#{alias=detector_pulses}{time_difference=1} between 0x1b3fb30 and 0x1b3fb30
Looking for pulses between 247590 and 267590 for ScGe#PassThrough#{alias=detector_pulses}{time_difference=1}
Looking for pulses between 247590 and 267590 for ScL#PassThrough#{alias=detector_pulses}{time_difference=1}
Looking for pulses between 247590 and 267590 for ScR#PassThrough#{alias=detector_pulses}{time_difference=1}
Looking for pulses between 247590 and 267590 for ScVe#PassThrough#{alias=detector_pulses}{time_difference=1}
Looking for pulses between 247590 and 267590 for SiL1-1#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
Looking for pulses between 247590 and 267590 for SiL1-2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
Looking for pulses between 247590 and 267590 for SiL1-3#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
Looking for pulses between 247590 and 267590 for SiL1-4#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
Looking for pulses between 247590 and 267590 for SiL2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
Looking for pulses between 247590 and 267590 for SiR1-1#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
Looking for pulses between 247590 and 267590 for SiR1-2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
Looking for pulses between 247590 and 267590 for SiR1-3#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
Looking for pulses between 247590 and 267590 for SiR1-4#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
Looking for pulses between 247590 and 267590 for SiR2#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
```

Now I'm just going to highlight the muSc pulses it's trying to add in each TME:

```
TME #0 (t = 257590) : 
Looking for pulses between 247590 and 267590 for muSc#PassThrough#{alias=detector_pulses}{time_difference=1}
TDP 0x1b404e0, t = 257590
Adding pulses from muSc#PassThrough#{alias=detector_pulses}{time_difference=1} between 0x1b404e0 and 0x1b3fc30
...
TME #1 (t = 367202) : 
Looking for pulses between 357202 and 377202 for muSc#PassThrough#{alias=detector_pulses}{time_difference=1}
TDP 0x1b404e0, t = 257590
TDP 0x1b3fc30, t = 367202
Adding pulses from muSc#PassThrough#{alias=detector_pulses}{time_difference=1} between 0x1b404e0 and 0x1b4e190
...
```

so the first muSc pulse is getting added to the second TME, even though it should be getting skipped over because it is outside the time window.

The generator finds the first pulse to look at in the following code:

``` C++
int look_ahead=1;
while((start+look_ahead!=end) && (start!=end) ){
    double time = (*(start+look_ahead))->GetTime();
    if(time==definitions::DefaultValue){
        // If time is DefaultValue then we're looking at an unpaired                                                                               
        // detector which we should ignore                                                                                                         
        ++look_ahead;
        continue;
    }
    look_ahead=1;
    if(time>early_edge) break;
    start+=look_ahead;
}
```

I can't see anything immeditaely wrong and the couple of things I've tried (mainly with the last if statement) haven't worked but I will look into it...

**Comment by AndrewEdmonds11** [comment] 2014-10-02 18:49
Ok, I made a few changes to the above bit of code

``` C++
@@ -93,23 +93,37 @@ void FixedWindowMEGenerator::AddPulsesInWindow(


     // Move the iteator for the start of the window
-    int look_ahead=1;
+    int look_ahead=0;
     while((start+look_ahead!=end) && (start!=end) ){
         double time = (*(start+look_ahead))->GetTime();
-        if(time==definitions::DefaultValue){
+
+        if(time==definitions::DefaultValue || time < early_edge){
             // If time is DefaultValue then we're looking at an unpaired
             // detector which we should ignore
+           // If the time is too early then maybe the next TDP will be OK
             ++look_ahead;
             continue;
         }
-        look_ahead=1;
-        if(time>early_edge) break;
-        start+=look_ahead;
+         if (time > late_edge) {
+           // If the first TDP in the container is too late for this TME
+           // then none of the future ones will be (they are time-order right?) 
+           // so we can return to avoid adding the first TDP to this TME anyway
+           // (which was also happening)
+           return;
+       }
+        if(time>early_edge) {
+         // So we've found the start and can now break from the while loop
+         start+=look_ahead;
+         look_ahead=1;
+         break;
+       }
     }
```

Hopefully, that makes sense. I'll leave Ben to confirm that this is OK but there turned out to be two things going on (the second of which I didn't notice).

First, we weren't checking that the first TDP was actually inside the time window (we were also breaking from the while loop before setting the `start` iterator to the correct place).

Secondly, we were adding the first TDP even if it was too late for this TME (e.g. the Ge TDP in the output below).

Here's some output from the first TME as it looks now:

```
TME #0 (t = 257590) : 
Looking for pulses between 247590 and 267590 for muSc#PassThrough#{alias=detector_pulses}{time_difference=1}
Checking for start:
Checking TDP 0x196d290: t = 257590 (valid - this is the start)
Checking for allowed TDPs:
TDP 0x196d290: t = 257590 (allowed)
TDP 0x196c9e0: t = 367202 (not allowed)
Adding pulses from muSc#PassThrough#{alias=detector_pulses}{time_difference=1} between 0x196d290 and 0x196c9e0
Looking for pulses between 247590 and 267590 for Ge#MaxTimeDiff#{alias=detector_pulses}{time_difference=1}
Checking for start:
Checking TDP 0x1978ee0: t = 377564 (not valid - too late)
Looking for pulses between 247590 and 267590 for NDet#PassThrough#{alias=detector_pulses}{time_difference=1}
Checking for start:
Checking TDP 0x196c8e0: t = 9.54248e+06 (not valid - too late)
```

As I said, I'll leave Ben to check this and make sure I haven't overlooked something important.

**Comment by AndrewEdmonds11** [comment] 2014-10-02 19:00
So, I didn't actually solve my initial problem of having the same TDP getting added so I needed to add another check using `valid_start`:

``` C++
@@ -93,19 +93,32 @@ void FixedWindowMEGenerator::AddPulsesInWindow(


     // Move the iteator for the start of the window
-    int look_ahead=1;
+    int look_ahead=0;
+    bool valid_start = false;
     while((start+look_ahead!=end) && (start!=end) ){
         double time = (*(start+look_ahead))->GetTime();
-        if(time==definitions::DefaultValue){
+
+        if(time==definitions::DefaultValue || time < early_edge){
             // If time is DefaultValue then we're looking at an unpaired
             // detector which we should ignore
             ++look_ahead;
             continue;
         }
-        look_ahead=1;
-        if(time>early_edge) break;
-        start+=look_ahead;
+         if (time > late_edge) {
+           // the first TDP in the container is too late for this TME
+           return;
+       }
+        if(time>early_edge) {
+         start+=look_ahead;
+         look_ahead=1;
+         valid_start = true;
+         break;
+       }
     }
+      if(!valid_start) {
+       // If we got this far and didn't find a valid start TDP then stop processing
+       return;
+      }
```

Just in case that there is only one TDP that is too early and not getting cleared up by the other checks

**Comment by benkrikler** [comment] 2014-10-28 20:58
Hey Andy,  
I've finally got round to looking at this, and I'm trying to see if I see the same problem, but I don't think I am.  I've checked the time distributions of TDPs against the central muon in a TME and things look healthy with no obvious spike that should occur when the same TDP is being put into many different TMEs.  I also zoomed in on the number of flags being set and I can see that the number of muon hits is greater than the number of TMEs with pile-up, although the fraction is pretty small.  I'm not sure yet if that's a bug or from the setup, but I'll look into it more.

Would you be able to run your previous checks to see if you still see the same problem?

**Comment by benkrikler** [comment] 2014-10-28 21:08
Ok, I think this is properly fixed now. 
![tme_tdiffs](https://cloud.githubusercontent.com/assets/4083697/4817081/723a8076-5ee5-11e4-802d-7460ab9cbd03.png)
There's enough physics in that plot that I'd like to spend more time on it and write it all up on an elog, but for me, the SiR2 exponential to the left shows this is working (this was a SiR2 active target run) as well as the symmetry on the muSc, and the small exponentials on other channels.  Also, the muon pile-up has dropped to about 18% as opposed to the 99.9% I had at the last comment.

The problem seems to have been in the loops to fill the TMEs in FixedWindowMEGenerator whose logic was bad.  It's a pretty complicated situation since I'm trying to be efficient and we have to handle 'bad', unpaired TDPs. 

Stupidly, I got confused about which branch I was working on though, so I'm going to tidy up the other work before I merge this in to develop, which will probably be tomorrow.

**Comment by AndrewEdmonds11** [comment] 2014-10-29 11:20
So do you want me to still check this, Ben? I'm fairly confident my problem was real...

**Comment by benkrikler** [comment] 2014-10-29 11:25
It might be good if you could double check things once I push this lot, but I think the problem is now fixed.  I (think I) simplified the loops to some degree so it should be easier to understand as well.

**Closed as completed** 2014-11-24 15:44 UTC
Labels: bug, Rootana
