### ISSUE TITLE
TAPGenerators do not get the options given to MakeAnalysedPulse

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#179] opened 2014-08-07 12:54 UTC
I'm not sure if this is by design but for the PulseCandidateFinder I had coded so that we could write something like this:

``` cfg
[ analyse_pulses ]
debug
analyse_channels=all
default_fast_generator=FirstComplete
default_slow_generator=FirstComplete
ScL_param=100
ScR_param=100
ScVe_param=100
```

where Sc*_param are the new parameter values to use but it seems that the generators aren't given the options that MakeAnalysedPulses use.

In any case, this may not be the way to go with this since, if we have to run over all the data, we would need different modules files for different channel-bank combinations. Maybe another SQLite database ;p

**Comment by benkrikler** [comment] 2014-08-07 13:09
This is by design.  If we ran with multiple generators how would each one know what option is for them?  

What do the `*_param` values describe?  

You can pass options to a generator through the constructor type interface, though for this sort of thing that might not be very readable.  Unfortunately that's all there is now, though for the next production we can extend it.  At this point, you could write:

```
default_fast_generator=FirstComplete( ScL_param=100, ScR_param=100, ScVe_param=100)
```

Since FirstComplete doesn't specify any named arguments this would fill options `"1"`, `"2"` and `"3"` with the `..._param=100` strings.  You could then loop over every option in the FirstComplete constructor and use the methods in ModulesParser.h to break up the key value pairs.

**Comment by AndrewEdmonds11** [comment] 2014-08-07 13:21
> This is by design. If we ran with multiple generators how would each one know what option is for them?

Well, the options for the PCF would be common to any generator that uses it. The *_param values are just the values for the thresholds in the fast and slow algorithms (the "rise" for the fast pulses and the "height" for the slow pulses)

For the time being I'll just hard-code the new values since the channels and banks are consistent over this dataset and we may need a better way of doing this anyway so will leave this open so that we can have that discussion at a later date.

**Comment by benkrikler** [comment] 2014-08-07 22:13
> Well, the options for the PCF would be common to any generator that uses it. 

But the PCF as well as any other algorithm or part of a generator may at some point want optimising.  If all options given to MakeAnalysedPulses were sent to every generator that would break.  If we only have one generator per channel then we can relax that a bit, but there are other ways we can go where we don't need to do this, for instance, using an aliased section approach as we do for the modules.

If these values have been optimised and aren't expected to be reconfigured on a run by run basis then a database might be the best way to do it.

**Comment by AndrewEdmonds11** [comment] 2014-11-24 16:14
Flagging this up since I'd like to use the debug option so that I can see that the parameters of the PulseCandidateFinder are actually getting set to.

There seems to have been a change to the code that means the debug flag is checked with `if (opts->GetFlag("debug"))`. Is there a special way to use this?

**Comment by benkrikler** [comment] 2014-11-24 16:26
`opts->GetFlag("debug")` is a slightly more flexible version of `GetBool`.  It returns true if the option `"debug"` is given and is not equal to false or 0 which means we can switch flag options off in the  modules file by equating them to false instead of needing to comment them out.  

Which part of the code are you looking at?  Is it `MakeAnalysedPulses`?

**Comment by AndrewEdmonds11** [comment] 2014-11-24 16:30
I'm looking in the PulseCandidateFinder.cpp file and I think the problem is that it doesn't get tiven the debug option from further up the chain (it's either not going from FirstComplete to PCF or MakeAnalysedPulses to FirstComplete).

**Comment by benkrikler** [comment] 2014-11-24 20:05
I've set this up so it works as you're asking.  It's a single commit added to develop that you can just pull. If you now run MakeAnalysedPulses with `debug` this will be passed onto the Generators and the FirstCompleteAPGenerator now passes this on again to PulseCandidateFinder.  Let me know if you have any issues with it...

**Comment by AndrewEdmonds11** [comment] 2014-11-25 10:17
Thanks, Ben. Works great.

**Comment by benkrikler** [comment] 2014-11-25 11:06
I'm going to close this then :)

**Closed as completed by benkrikler** 2014-11-25 11:06 UTC
Labels: Enhancement, Rootana
